application: nacelle-microframework
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /media
  static_dir: media
- url: /.*
  script: nacelle.app.wsgi

inbound_services:
- warmup

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "latest"
