#!/bin/bash

# Nacelle Microframework
# Copyright (c) Patrick Carey 2012
#
# This is a simple script to automate the process of copying the
# appengine datastore into RAM before running.  This gives a ~10x
# speedup on datastore operations locally.  Probably only works on
# Ubuntu (see: haven't bothered to check)


if [ -f ".datastore" ]; then
    echo "Copying datastore into RAM"
    cp .datastore /run/shm/datastore
fi

echo "Running dev_appserver"
dev_appserver.py . --use_sqlite --datastore_path=/run/shm/datastore --enable_sendmail

if [ -f "/run/shm/datastore" ]; then
    echo "Copying datastore back to project directory"
    cp /run/shm/datastore .datastore
fi

echo "Exiting..."
